env:
#  - NODE_VERSION=0.10
  - NODE_VERSION=0.12
#  - NODE_VERSION=iojs

sudo: false

os:
#  - osx
  - linux

install:
  - test $TRAVIS_OS_NAME = "osx" && brew update && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux" && which nvm
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - node --version
  - npm --version
  - npm install

script:
  - npm test

after_success: npm run coveralls

matrix:
  allow_failures:
    - os: osx
  fast_finish: true

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8c1769bff63cbd033bf7
    on_success: always
    on_failure: always
    on_start: false

